import test from 'node:test'
import assert from 'node:assert/strict'
import {restoreAccessView} from '../app/access-api.mjs'
const incomplete={id:'student-1',profileSetupCompleted:false,avatarId:null},complete={...incomplete,profileSetupCompleted:true,avatarId:'avatar_boy_02'}
function getWith({student,pending={status:'NONE'},teacher}={}){return async path=>path==='/api/student/me'?{student}:path==='/api/student/access/status'?pending:{teacher}}
test('refresh preserves an authenticated section and cannot repeat completed onboarding',async()=>{for(const savedScreen of ['profile','practice','fipi'])assert.equal((await restoreAccessView({savedScreen,get:getWith({student:complete})})).screen,savedScreen);for(const savedScreen of ['avatar-setup','avatar-done','avatar-edit','landing'])assert.equal((await restoreAccessView({savedScreen,get:getWith({student:complete})})).screen,'home')})
test('only a server session can restore an app page; an unfinished server profile always opens setup',async()=>{assert.equal((await restoreAccessView({savedScreen:'profile',get:getWith()})).screen,'landing');assert.equal((await restoreAccessView({savedScreen:'profile',requestedScreen:'home',get:getWith({student:incomplete})})).screen,'avatar-setup');assert.equal((await restoreAccessView({get:getWith({student:complete})})).screen,'home')})
test('refresh restores pending requests and approval automatically chooses the proper next screen',async()=>{const pending=await restoreAccessView({savedScreen:'pending',get:getWith({pending:{status:'PENDING',requestId:'real-request',className:'8Б'}})});assert.equal(pending.screen,'pending');assert.equal(pending.request.id,'real-request');assert.equal((await restoreAccessView({get:getWith({pending:{status:'APPROVED',student:incomplete}})})).screen,'avatar-setup');assert.equal((await restoreAccessView({get:getWith({pending:{status:'APPROVED',student:complete}})})).screen,'home');assert.equal((await restoreAccessView({savedScreen:'pending',get:getWith()})).request.status,'EXPIRED')})
test('teacher refresh requires the real teacher session and network failure cannot become a fake login',async()=>{assert.equal((await restoreAccessView({savedScreen:'teacher',get:getWith({teacher:{id:'teacher-1'}})})).screen,'teacher');assert.equal((await restoreAccessView({savedScreen:'teacher',get:getWith()})).screen,'landing');await assert.rejects(()=>restoreAccessView({get:async()=>{throw new Error('offline')}}),/offline/)})
