'use client'
import styles from './connection-screen.module.css'
export default function ConnectionScreen({request,teacher=false,onHome,onApprove,onReject,onOpen,onRetry,onDemo,brand}){
 const approved=request?.status==='APPROVED', rejected=request?.status==='REJECTED', empty=!request
 const title=empty?'Новых запросов нет':approved?'Подключение подтверждено':rejected?'Запрос отклонён':teacher?'Запрос на подключение':'Ждём подтверждения'
 const description=empty?'Когда ученик введёт выданный код, запрос появится здесь.':approved?(teacher?'Подключение ученика подтверждено. Доступ к Genius открыт.':'Учитель подтвердил подключение. Можно входить в Genius.'):rejected?'Учитель не подтвердил этот запрос. Для подключения нужен новый код.':teacher?'Ученик ввёл выданный код. Подтвердите подключение к классу или отклоните запрос.':'Код проверен. Запрос отправлен учителю и пока не даёт доступ к учебным данным.'
 const number=request?.codeLabel?.match(/\d+/)?.[0]
 return <section className={`${styles.scene} ${teacher?styles.teacher:''}`} aria-label={teacher?'Подключение ученика':'Статус подключения'}><div className={styles.panel} data-status={approved?'approved':rejected?'rejected':'pending'}>{brand||<button className={styles.brand} onClick={onHome}><svg viewBox="0 0 50 50" aria-hidden="true"><g fill="none" stroke="currentColor" strokeWidth="2"><ellipse cx="25" cy="25" rx="22" ry="9"/><ellipse cx="25" cy="25" rx="22" ry="9" transform="rotate(60 25 25)"/><ellipse cx="25" cy="25" rx="22" ry="9" transform="rotate(120 25 25)"/></g><circle cx="25" cy="25" r="4" fill="currentColor"/></svg><span>Genius</span></button>}<div className={styles.status} aria-hidden="true">{approved||empty?'✓':rejected?'×':'···'}</div><h1>{title}</h1><p className={styles.description}>{description}</p>{request&&<div className={styles.summary}><span>{request.className}</span><div><strong>Класс {request.className}{number?` (${number})`:''}</strong><small>Запрос: {request.requestedAt}</small></div></div>}
 {teacher&&!empty&&!approved&&!rejected?<div className={styles.actions}><button className={styles.primary} onClick={onApprove}>Подтвердить подключение</button><button className={styles.reject} onClick={onReject}>Отклонить запрос</button></div>:approved?<button className={styles.primary} onClick={onOpen}>{teacher?'Открыть экран ученика (демо)':'Открыть Genius →'}</button>:rejected?<button className={styles.primary} onClick={teacher?onOpen:onRetry}>{teacher?'Открыть экран ученика (демо)':'Ввести другой код'}</button>:!empty?<><div className={styles.note}><span aria-hidden="true">◷</span>В рабочей версии этот экран будет автоматически проверять статус запроса.</div><button className={styles.soft} onClick={onDemo}>Открыть вход учителя для демо</button></>:null}
 <button className={styles.home} onClick={onHome}>{teacher?'Вернуться к моим классам':'Вернуться на главную'}</button></div></section>
}
