'use client';
import {useEffect,useState} from 'react';
const tasks=[
{id:1,subject:'Математика',level:'Легко',xp:20,q:'Решите уравнение: 3x + 7 = 22',answer:'5',hint:'Перенеси 7 вправо, затем раздели на 3.'},
{id:2,subject:'Математика',level:'Средне',xp:35,q:'Найдите площадь прямоугольника 8 × 7 см.',answer:'56',hint:'S = a × b.'},
{id:3,subject:'Физика',level:'Средне',xp:40,q:'Тело прошло 120 м за 20 с. Найдите скорость в м/с.',answer:'6',hint:'v = s / t.'},
{id:4,subject:'Информатика',level:'Легко',xp:25,q:'Сколько бит содержится в одном байте?',answer:'8',hint:'Это базовое соотношение единиц информации.'},
{id:5,subject:'Математика',level:'Сложно',xp:60,q:'Найдите дискриминант: x² − 5x + 6 = 0.',answer:'1',hint:'D = b² − 4ac.'}
];
const leaders=[['Алина',420],['Максим',365],['София',330],['Илья',295]];
export default function Home(){const [active,setActive]=useState(tasks[0]);const [answer,setAnswer]=useState('');const [xp,setXp]=useState(0);const [solved,setSolved]=useState<number[]>([]);const [message,setMessage]=useState('');const [hint,setHint]=useState(false);
useEffect(()=>{try{setXp(Number(localStorage.getItem('97xp')||0));setSolved(JSON.parse(localStorage.getItem('97solved')||'[]'))}catch{}},[]);
function check(){if(answer.trim().replace(',','.')===active.answer){let next=xp;if(!solved.includes(active.id)){next=xp+active.xp;const s=[...solved,active.id];setSolved(s);setXp(next);localStorage.setItem('97solved',JSON.stringify(s));localStorage.setItem('97xp',String(next))}setMessage('Верно! XP начислены 🎉')}else setMessage('Пока неверно. Попробуй ещё раз.');}
const progress=Math.round(solved.length/tasks.length*100);return <main><header><a className="logo" href="#">97<span>school</span></a><nav><a href="#tasks">Задачи</a><a href="#rating">Рейтинг</a><a href="#profile">Профиль</a></nav><b>⚡ {xp} XP</b></header><section className="hero"><div><small>УЧИСЬ • РЕШАЙ • РАСТИ</small><h1>Прокачивай знания.<br/><i>Поднимайся в рейтинге.</i></h1><p>Решай школьные задачи, получай очки опыта и соревнуйся с другими учениками.</p><a className="primary" href="#tasks">Начать решать →</a></div><aside><label>Твой прогресс</label><strong>{progress}%</strong><div className="bar"><span style={{width:progress+'%'}}/></div><p>Решено {solved.length} из {tasks.length} задач</p><hr/><div><span>Уровень</span><b>{xp>=100?'Исследователь':'Новичок'}</b></div><div><span>Опыт</span><b>{xp} XP</b></div></aside></section><section id="tasks"><small>ТРЕНИРОВКА</small><h2>Задачи</h2><div className="workspace"><div className="list">{tasks.map(t=><button className={active.id===t.id?'active':''} key={t.id} onClick={()=>{setActive(t);setAnswer('');setMessage('');setHint(false)}}><b>{solved.includes(t.id)?'✓':'0'+t.id}</b><span><strong>{t.subject}</strong><small>{t.level} · +{t.xp} XP</small></span></button>)}</div><article><div className="tags"><span>{active.subject}</span><span>{active.level}</span><span>+{active.xp} XP</span></div><h3>{active.q}</h3><label>Твой ответ</label><input value={answer} onChange={e=>setAnswer(e.target.value)} onKeyDown={e=>e.key==='Enter'&&check()} placeholder="Введите ответ"/><div className="actions"><button className="primary" onClick={check}>Проверить</button><button onClick={()=>setHint(!hint)}>Подсказка</button></div>{hint&&<p className="notice">💡 {active.hint}</p>}{message&&<p className="notice">{message}</p>}</article></div></section><section id="rating" className="rating"><div><small>СОРЕВНОВАНИЕ</small><h2>Таблица лидеров</h2><p>Зарабатывай XP и поднимайся выше.</p></div><div className="board">{leaders.map((x,i)=><div key={x[0]}><b>#{i+1}</b><span className="avatar">{x[0][0]}</span><strong>{x[0]}</strong><em>{x[1]} XP</em></div>)}<div className="you"><b>—</b><span className="avatar">Я</span><strong>Ты</strong><em>{xp} XP</em></div></div></section><section id="profile"><small>ПРОФИЛЬ</small><h2>Твоя статистика</h2><div className="stats"><div>⚡<b>{xp}</b><span>XP</span></div><div>✓<b>{solved.length}</b><span>решено</span></div><div>◎<b>{progress}%</b><span>прогресс</span></div></div></section><footer><b>97school</b><span>MVP · учимся через практику</span></footer></main>}